"""Tier 3 null-hypothesis test: separate vanilla vs. jailbroken self-chat
rollouts on the `freedom` seed using per-message embedding aggregations.

Recycles the per-message nomic embedding substrate from Phase 3
(`artifacts/emb_msgs.npz`, produced by `selfchat.embeddings.embed_messages`).

Four fitting modes — all in this script — to probe *where* a V/JB
embedding-level difference (if any) lives:

  A. mean       — per-run mean of message vectors  (n_runs, D)
  B. terminal   — last-message vector per run       (n_runs, D)
  C. mean_std   — concat(mean, std) per run         (n_runs, 2D)
  D. per_msg    — classifier on individual messages,
                   aggregated to per-run prob via mean.
                   GroupKFold on run_id so a run's other turns
                   never leak into training.

Mode D is conceptually distinct: each message is generated by the
process being tested, so per-turn classification probes the generative
process directly rather than collapsing each conversation to one point.

Run:
  python -m selfchat.classify.tier3_embeddings
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression  # type: ignore[import-not-found]
from sklearn.model_selection import (  # type: ignore[import-not-found]
    RepeatedStratifiedKFold,
    StratifiedGroupKFold,
    train_test_split,
)
from sklearn.metrics import roc_auc_score, accuracy_score, confusion_matrix  # type: ignore[import-not-found]
from sklearn.pipeline import Pipeline  # type: ignore[import-not-found]
from sklearn.preprocessing import StandardScaler  # type: ignore[import-not-found]

from selfchat.classify._common import DEFAULT_SEED, TierResult


DEFAULT_EMB = Path("artifacts/emb_msgs.npz")
DEFAULT_SEED_FILTER = DEFAULT_SEED


# ---------------------------------------------------------------------------
# data loading
# ---------------------------------------------------------------------------


def load_emb(path: Path, seed_filter: str) -> dict[str, np.ndarray]:
    """Load `emb_msgs.npz` and filter to `seed_filter` rows.

    Returns a dict of (n_msgs,)/(n_msgs, D) arrays restricted to that seed.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found — run `python -m selfchat.embeddings.embed_messages "
            f"<transcript-dir> --out {path}` first"
        )
    d = np.load(path)
    seeds = d["seeds"]
    mask = seeds == seed_filter
    if not mask.any():
        unique = sorted(set(seeds.tolist()))
        raise RuntimeError(
            f"no rows with seed='{seed_filter}' in {path}. "
            f"Available seeds: {unique}"
        )
    out = {
        "vectors": d["vectors"][mask],
        "run_ids": d["run_ids"][mask],
        "turn_index": d["turn_index"][mask],
        "variants": d["variants"][mask],
    }
    return out


def aggregate_per_run(
    msgs: dict[str, np.ndarray],
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, list[str]]:
    """Group messages by run_id, return (X_mean, X_terminal, X_mean_std, y, run_ids).

    Within each run, sort messages by `turn_index` ascending; terminal is
    the highest-turn-index message.
    """
    vectors = msgs["vectors"]
    run_ids = msgs["run_ids"]
    turn_index = msgs["turn_index"]
    variants = msgs["variants"]

    unique_runs: list[str] = []
    seen: set[str] = set()
    for r in run_ids.tolist():
        if r not in seen:
            unique_runs.append(r)
            seen.add(r)

    means: list[np.ndarray] = []
    terms: list[np.ndarray] = []
    mstds: list[np.ndarray] = []
    y: list[int] = []

    for r in unique_runs:
        idx = np.where(run_ids == r)[0]
        v = vectors[idx]
        ti = turn_index[idx]
        order = np.argsort(ti)
        v_sorted = v[order]
        means.append(v_sorted.mean(axis=0))
        terms.append(v_sorted[-1])
        mstds.append(np.concatenate([v_sorted.mean(axis=0), v_sorted.std(axis=0)]))
        y.append(1 if variants[idx[0]] == "jailbroken" else 0)

    return (
        np.array(means),
        np.array(terms),
        np.array(mstds),
        np.array(y, dtype=np.int64),
        unique_runs,
    )


# ---------------------------------------------------------------------------
# pooled-feature evaluators (modes A/B/C)
# ---------------------------------------------------------------------------


def _make_pipe(seed: int) -> Pipeline:
    return Pipeline([
        ("scale", StandardScaler()),
        ("clf", LogisticRegression(max_iter=2000, C=1.0, random_state=seed)),
    ])


def cv_eval_pooled(
    X: np.ndarray, y: np.ndarray, seed: int = 0
) -> tuple[np.ndarray, np.ndarray]:
    skf = RepeatedStratifiedKFold(n_splits=5, n_repeats=5, random_state=seed)
    accs, aucs = [], []
    for tr, te in skf.split(X, y):
        pipe = _make_pipe(seed)
        pipe.fit(X[tr], y[tr])
        proba = pipe.predict_proba(X[te])[:, 1]
        pred = (proba >= 0.5).astype(int)
        accs.append(accuracy_score(y[te], pred))
        aucs.append(roc_auc_score(y[te], proba))
    return np.array(accs), np.array(aucs)


def holdout_eval_pooled(
    X: np.ndarray, y: np.ndarray, seed: int = 0
) -> tuple[float, float, np.ndarray]:
    Xtr, Xte, ytr, yte = train_test_split(
        X, y, test_size=0.3, stratify=y, random_state=seed
    )
    pipe = _make_pipe(seed)
    pipe.fit(Xtr, ytr)
    proba = pipe.predict_proba(Xte)[:, 1]
    pred = (proba >= 0.5).astype(int)
    return (
        float(accuracy_score(yte, pred)),
        float(roc_auc_score(yte, proba)),
        confusion_matrix(yte, pred),
    )


def run_pooled(label: str, X: np.ndarray, y: np.ndarray) -> None:
    print(f"\n=== {label}  (X shape {X.shape}) ===")
    accs, aucs = cv_eval_pooled(X, y)
    print(f"  5×5 repeated CV: acc = {accs.mean():.3f} ± {accs.std():.3f}  "
          f"|  AUC = {aucs.mean():.3f} ± {aucs.std():.3f}")
    acc, auc, cm = holdout_eval_pooled(X, y)
    print(f"  70/30 holdout (seed=0):  acc = {acc:.3f}  |  AUC = {auc:.3f}")
    print("    confusion matrix [rows=true V/JB, cols=pred V/JB]:")
    print(f"      [[{cm[0,0]:>3} {cm[0,1]:>3}]")
    print(f"       [{cm[1,0]:>3} {cm[1,1]:>3}]]")


# ---------------------------------------------------------------------------
# per-message classify-then-aggregate (mode D)
# ---------------------------------------------------------------------------


def per_msg_aggregate_stats(
    msgs: dict[str, np.ndarray], seed: int = 0
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Mode D core: returns (msg_accs, msg_aucs, run_accs, run_aucs).

    StratifiedGroupKFold respects both class balance and group integrity
    (a run's messages are never split across train/test). Loops over 5
    random seeds for 5×5 = 25 total splits — matches the repeated-CV
    scheme used in modes A/B/C.
    """
    X = msgs["vectors"]
    run_ids = msgs["run_ids"]
    y_msg = (msgs["variants"] == "jailbroken").astype(int)

    msg_accs, msg_aucs = [], []
    run_accs, run_aucs = [], []

    for repeat_seed in range(5):
        sgkf = StratifiedGroupKFold(
            n_splits=5, shuffle=True, random_state=repeat_seed
        )
        for tr, te in sgkf.split(X, y_msg, groups=run_ids):
            pipe = _make_pipe(seed)
            pipe.fit(X[tr], y_msg[tr])
            proba_msg = pipe.predict_proba(X[te])[:, 1]
            pred_msg = (proba_msg >= 0.5).astype(int)
            msg_accs.append(accuracy_score(y_msg[te], pred_msg))
            msg_aucs.append(roc_auc_score(y_msg[te], proba_msg))

            run_te = run_ids[te]
            unique_te = sorted(set(run_te.tolist()))
            proba_run = np.array(
                [proba_msg[run_te == r].mean() for r in unique_te]
            )
            y_run = np.array(
                [y_msg[te][run_te == r][0] for r in unique_te], dtype=np.int64
            )
            pred_run = (proba_run >= 0.5).astype(int)
            run_accs.append(accuracy_score(y_run, pred_run))
            run_aucs.append(roc_auc_score(y_run, proba_run))

    return (
        np.array(msg_accs), np.array(msg_aucs),
        np.array(run_accs), np.array(run_aucs),
    )


def run_per_msg_aggregate(msgs: dict[str, np.ndarray], seed: int = 0) -> None:
    print(f"\n=== mode D: per-message classify-then-aggregate "
          f"(n_msgs={len(msgs['vectors'])}, "
          f"n_runs={len(set(msgs['run_ids'].tolist()))}) ===")
    msg_accs, msg_aucs, run_accs, run_aucs = per_msg_aggregate_stats(msgs, seed)
    print(f"  message-level 5×5 (StratifiedGroupKFold): "
          f"acc = {msg_accs.mean():.3f} ± {msg_accs.std():.3f}  "
          f"|  AUC = {msg_aucs.mean():.3f} ± {msg_aucs.std():.3f}")
    print(f"  run-level (mean-prob aggregate):           "
          f"acc = {run_accs.mean():.3f} ± {run_accs.std():.3f}  "
          f"|  AUC = {run_aucs.mean():.3f} ± {run_aucs.std():.3f}")


def run(
    seed: str = DEFAULT_SEED,
    emb_path: Path = DEFAULT_EMB,
) -> list[TierResult]:
    """Programmatic entry point used by the suite runner.

    Returns 5 TierResults: modes A/B/C, plus mode D run-level and msg-level.
    Tier 3 features are opaque embedding dims, so feature lists stay empty.
    """
    msgs = load_emb(emb_path, seed)
    n_runs = len(set(msgs["run_ids"].tolist()))
    n_msgs = len(msgs["vectors"])
    X_mean, X_term, X_mstd, y, _ = aggregate_per_run(msgs)

    out: list[TierResult] = []
    for X, label in [
        (X_mean, "emb mean (A)"),
        (X_term, "emb terminal (B)"),
        (X_mstd, "emb mean‖std (C)"),
    ]:
        accs, aucs = cv_eval_pooled(X, y)
        h_acc, h_auc, _ = holdout_eval_pooled(X, y)
        out.append(
            TierResult(
                tier="3",
                mode=label,
                n=n_runs,
                cv_acc_mean=float(accs.mean()),
                cv_acc_std=float(accs.std()),
                cv_auc_mean=float(aucs.mean()),
                cv_auc_std=float(aucs.std()),
                holdout_acc=h_acc,
                holdout_auc=h_auc,
            )
        )

    msg_accs, msg_aucs, run_accs, run_aucs = per_msg_aggregate_stats(msgs)
    out.append(
        TierResult(
            tier="3",
            mode="emb per-msg (D, run-level)",
            n=n_runs,
            cv_acc_mean=float(run_accs.mean()),
            cv_acc_std=float(run_accs.std()),
            cv_auc_mean=float(run_aucs.mean()),
            cv_auc_std=float(run_aucs.std()),
        )
    )
    out.append(
        TierResult(
            tier="3",
            mode="emb per-msg (D, msg-level)",
            n=n_msgs,
            cv_acc_mean=float(msg_accs.mean()),
            cv_acc_std=float(msg_accs.std()),
            cv_auc_mean=float(msg_aucs.mean()),
            cv_auc_std=float(msg_aucs.std()),
        )
    )
    return out


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--emb",
        type=Path,
        default=DEFAULT_EMB,
        help=f"Per-message embedding npz (default: {DEFAULT_EMB})",
    )
    p.add_argument(
        "--seed-name",
        default=DEFAULT_SEED_FILTER,
        help=f"Seed name to filter to (default: {DEFAULT_SEED_FILTER})",
    )
    args = p.parse_args()

    print(f"loading {args.emb} (seed='{args.seed_name}') ...")
    msgs = load_emb(args.emb, args.seed_name)
    n_msgs = len(msgs["vectors"])
    n_runs = len(set(msgs["run_ids"].tolist()))
    n_v_runs = len(set(
        msgs["run_ids"][msgs["variants"] == "vanilla"].tolist()
    ))
    n_j_runs = len(set(
        msgs["run_ids"][msgs["variants"] == "jailbroken"].tolist()
    ))
    print(f"  n_msgs={n_msgs}, n_runs={n_runs}  "
          f"(vanilla={n_v_runs}, jailbroken={n_j_runs}), "
          f"D={msgs['vectors'].shape[1]}")

    X_mean, X_term, X_mstd, y, _ = aggregate_per_run(msgs)

    run_pooled("mode A: per-run MEAN of message vectors", X_mean, y)
    run_pooled("mode B: per-run TERMINAL message vector", X_term, y)
    run_pooled("mode C: per-run MEAN ‖ STD concatenated", X_mstd, y)
    run_per_msg_aggregate(msgs)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
